
--DATA WAREHOUSE INVENTORY MANAGEMENT--

CREATE DATABASE INVMAN
USE INVMAN
------------------------------------------------------------------
CREATE TABLE PRODUCT(
PID CHAR (6) PRIMARY KEY,
PDESC VARCHAR(100) NOT NULL,
PRICE FLOAT CHECK (PRICE != 0),
CATEGORY CHAR(2) CHECK (CATEGORY = 'IT' OR CATEGORY = 'HA' OR CATEGORY = 'HC'),
SID CHAR(6) 
)

ALTER TABLE PRODUCT 
ADD CONSTRAINT FKSID 
FOREIGN KEY (SID) REFERENCES SUPPLIER(SID)

---------------------------------------------------------------


CREATE TABLE SUPPLIER(
SID CHAR (6) PRIMARY KEY,
SNAME VARCHAR(20) NOT NULL,
SADD VARCHAR (50) NOT NULL,
SCITY CHAR(5) CHECK (SCITY = 'DELHI'),
SPHONE CHAR(10) UNIQUE,
SEMAIL VARCHAR(20)
)
-------------------------------------------------------------

CREATE TABLE ORDERS(
OID CHAR(6) PRIMARY KEY,
ODATE DATE,
CID CHAR(6),
PID CHAR(6) FOREIGN KEY REFERENCES PRODUCT(PID),
OQTY INT CHECK (OQTY >= 1)
)
 DROP TABLE ORDERS 

SELECT * FROM ORDERS

ALTER TABLE ORDERS 
ADD CONSTRAINT FKCID 
FOREIGN KEY (CID) REFERENCES CUSTOMER(CID)
-----------------------------------------------


CREATE TABLE CUSTOMER(
CID CHAR(6) PRIMARY KEY,
CNAME VARCHAR(30) NOT NULL,
ADDRESS VARCHAR(30) NOT NULL,
CITY VARCHAR(30) NOT NULL,
PHONE CHAR(10) NOT NULL,
EMAIL VARCHAR(30) NOT NULL,
DOB DATE CHECK (DOB >= '01-01-2000') 
)


-------------------------------------------------
CREATE TABLE STOCK(
PID CHAR(6) FOREIGN KEY REFERENCES PRODUCT(PID),
SQTY INT CHECK (SQTY >= 0),
ROL INT CHECK (ROL >0),
MOQ INT CHECK (MOQ >=5)
)

CREATE TABLE BILL(
OID CHAR(6) FOREIGN KEY REFERENCES ORDERS(OID),
ODATE DATE,
CNAME VARCHAR(20),
ADDR VARCHAR(20),
PHONE CHAR(10),
PDESC VARCHAR(20),
PRICE VARCHAR(20),
OQTY  INT,
AMT FLOAT NOT NULL
)

SELECT PRODUCT.PID, PDESC, CATEGORY,SNAME, SCITY FROM PRODUCT 
INNER JOIN SUPPLIER 
ON PRODUCT.SID = SUPPLIER.SID

SELECT OID,ODATE,OQTY, CNAME, ADDRESS, PHONE FROM ORDERS , CUSTOMER  


